### ISSUE TITLE
code

### ISSUE THREAD

**Issue by DreamerDW** [MysteryVaibhav/RWR-GAE#1]
Hi,

When I run the code, such an error occurs, what is the reason?
Thanks！
Traceback (most recent call last):
  File "train.py", line 201, in <module>
    gae_for(args)
  File "train.py", line 120, in gae_for
    curr_pair = (int(walk[center_node_pos]), [])
NameError: name 'center_node_pos' is not defined
  File "train.py", line 119, in gae_for
    curr_pair = (int(walk[center_node_pos]), [])
UnboundLocalError: local variable 'center_node_pos' referenced before assignment

**Comment by xcgydfjjjderg** [comment]
> Hi,
> 
> When I run the code, such an error occurs, what is the reason? Thanks！ Traceback (most recent call last): File "train.py", line 201, in gae_for(args) File "train.py", line 120, in gae_for curr_pair = (int(walk[center_node_pos]), []) NameError: name 'center_node_pos' is not defined File "train.py", line 119, in gae_for curr_pair = (int(walk[center_node_pos]), []) UnboundLocalError: local variable 'center_node_pos' referenced before assignment

Did you solve it, I have the same problem. And I emailed the author with no response. Thank you very much.
