### ISSUE TITLE
There is a big difference between the experimental data and the actual operation results

### ISSUE THREAD

**Issue by lilinbaba** [MysteryVaibhav/RWR-GAE#3]
I read your paper and I'm interested in it. But I have doubts about the detailed implementation process of the algorithm.I run your open source code and find that the actual results are quite different from the data in the paper. Can you provide all the parameters needed to run the code?

**Comment by CHERYZ** [comment]
+1

**Comment by xcgydfjjjderg** [comment]
I also encountered the same problem. There is a gap between the experimental results and the original paper when I downloaded the open source code according to the instructions in the README file. Could you please give all the parameters, thank you very much.

**Comment by xcgydfjjjderg** [comment]
> I read your paper and I'm interested in it. But I have doubts about the detailed implementation process of the algorithm.I run your open source code and find that the actual results are quite different from the data in the paper. Can you provide all the parameters needed to run the code?

Did you solve it, I have the same problem. And I emailed the author with no response. I plan to use this as the opening topic of the thesis, but there is a gap in the experimental data, so please let me know if you have solved it. Thank you very much.

**Comment by xcgydfjjjderg** [comment]
> Did you solve it, I have the same problem. And I emailed the author with no response. I plan to use this as the opening topic of the thesis, but there is a gap in the experimental data, so please let me know if you have solved it. Thank you very much.

Did you solve it, I have the same problem. And I emailed the author with no response. I plan to use this as the opening topic of the thesis, but there is a gap in the experimental data, so please let me know if you have solved it. Thank you very much.

**Comment by xcgydfjjjderg** [comment]
> +1

Did you solve it, I have the same problem. And I emailed the author with no response. I plan to use this as the opening topic of the thesis, but there is a gap in the experimental data, so please let me know if you have solved it. Thank you very much.

**Comment by lilinbaba** [comment]
Not resolved. I think the author has academic fraud!
&nbsp;


李琳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月30日(星期天) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MysteryVaibhav/RWR-GAE] There is a big difference between the experimental data and the actual operation results (#3)





  
Did you solve it, I have the same problem. And I emailed the author with no response. I plan to use this as the opening topic of the thesis, but there is a gap in the experimental data, so please let me know if you have solved it. Thank you very much.
  
Did you solve it, I have the same problem. And I emailed the author with no response. I plan to use this as the opening topic of the thesis, but there is a gap in the experimental data, so please let me know if you have solved it. Thank you very much.

**Comment by lilinbaba** [comment]
Not resolved. I think the author has academic fraud!
&nbsp;


李琳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月30日(星期天) 下午5:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MysteryVaibhav/RWR-GAE] There is a big difference between the experimental data and the actual operation results (#3)





  
+1
  
Did you solve it, I have the same problem. And I emailed the author with no response. I plan to use this as the opening topic of the thesis, but there is a gap in the experimental data, so please let me know if you have solved it. Thank you very much.

**Comment by xcgydfjjjderg** [comment]
> 

我也觉得我还打算用它开题，开题报告都写好了下周就开了但是我实验跑出来有差距，我尝试过调参但是也没效果。我给作者发邮件两个是假的，只有一个账号能发但是一直没收到回复。然后尝试按照代码输入参数，但是当我输入--context=1代码就报错。怎么办要死了。Traceback (most recent call last):
File "train.py", line 201, in
gae_for(args)
File "train.py", line 120, in gae_for
curr_pair = (int(walk[center_node_pos]), [])
NameError: name 'center_node_pos' is not defined
File "train.py", line 119, in gae_for
curr_pair = (int(walk[center_node_pos]), [])
UnboundLocalError: local variable 'center_node_pos' referenced before assignment

**Comment by lilinbaba** [comment]
能跑，就是结果不对，想跑的话可以调代码，不要再考虑改进了
&nbsp;


李琳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月30日(星期天) 下午5:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MysteryVaibhav/RWR-GAE] There is a big difference between the experimental data and the actual operation results (#3)





   
我也觉得我还打算用它开题，开题报告都写好了下周就开了但是我实验跑出来有差距，我尝试过调参但是也没效果。我给作者发邮件两个是假的，只有一个账号能发但是一直没收到回复。然后尝试按照代码输入参数，但是当我输入--context=1代码就报错。怎么办要死了。Traceback (most recent call last):
 File "train.py", line 201, in
 gae_for(args)
 File "train.py", line 120, in gae_for
 curr_pair = (int(walk[center_node_pos]), [])
 NameError: name 'center_node_pos' is not defined
 File "train.py", line 119, in gae_for
 curr_pair = (int(walk[center_node_pos]), [])
 UnboundLocalError: local variable 'center_node_pos' referenced before assignment

**Comment by xcgydfjjjderg** [comment]
> 能跑，就是结果不对，想跑的话可以调代码，不要再考虑改进了 &nbsp; 李琳 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年10月30日(星期天) 下午5:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [MysteryVaibhav/RWR-GAE] There is a big difference between the experimental data and the actual operation results (#3) 我也觉得我还打算用它开题，开题报告都写好了下周就开了但是我实验跑出来有差距，我尝试过调参但是也没效果。我给作者发邮件两个是假的，只有一个账号能发但是一直没收到回复。然后尝试按照代码输入参数，但是当我输入--context=1代码就报错。怎么办要死了。Traceback (most recent call last): File "train.py", line 201, in gae_for(args) File "train.py", line 120, in gae_for curr_pair = (int(walk[center_node_pos]), []) NameError: name 'center_node_pos' is not defined File "train.py", line 119, in gae_for curr_pair = (int(walk[center_node_pos]), []) UnboundLocalError: local variable 'center_node_pos' referenced before assignment — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



> 

哥/姐你也是研究这块的吗？开题要创新点，我都担心我后续实验能不能跑出论文的效果可能效果差就完蛋了。我最近把另一篇论文的一个创新点引入但是效果很差在这个模型上跑，感觉要崩了。

**Comment by xcgydfjjjderg** [comment]
李琳学姐您好，冒昧打扰您还请您见谅。因为没有您的邮箱，所以只能以这样的方式来联系您。我想向您请教一个问题，还是关于国外那篇重启随机游走的图自编码器。就是那个论文的模型结构我还是没搞懂，我不知道我的理解对不对所以向您请教，打扰您还请您见谅。问题是这样的原本的图自编码器不是经过两层图卷积得到节点的嵌入表示矩阵Z,而那篇英文是为了改进低嵌入问题利用重启的随机游走得到节点的嵌入表示矩阵Z.那这两个Z是替代关系吗？就是随机游走得到的Z替代了原始模型训练出来的Z，还是说是把这两个Z组合起来？恳请学姐能帮忙解惑一下，我将万分感激，跪谢！因为我的学校比较差是个二本学院，虽然我的老师很好很负责但是这块的学术问题他不懂，图神经网络这个方向目前是我自己在摸索没人指导，所以有些问题不知道找谁帮忙，冒昧打扰学姐您，还请见谅谢谢。


------------------

落月成孤倚灬
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Sunday, Oct 30, 2022 5:17 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [MysteryVaibhav/RWR-GAE] There is a big difference between the experimental data and the actual operation results (#3)





 能跑，就是结果不对，想跑的话可以调代码，不要再考虑改进了 
 &amp;nbsp; 
 
 
 李琳 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年10月30日(星期天) 下午5:16 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [MysteryVaibhav/RWR-GAE] There is a big difference between the experimental data and the actual operation results (#3) 
 
 
 
 
 
     
 我也觉得我还打算用它开题，开题报告都写好了下周就开了但是我实验跑出来有差距，我尝试过调参但是也没效果。我给作者发邮件两个是假的，只有一个账号能发但是一直没收到回复。然后尝试按照代码输入参数，但是当我输入--context=1代码就报错。怎么办要死了。Traceback (most recent call last): 
  File "train.py", line 201, in 
  gae_for(args) 
  File "train.py", line 120, in gae_for 
  curr_pair = (int(walk[center_node_pos]), []) 
  NameError: name 'center_node_pos' is not defined 
  File "train.py", line 119, in gae_for 
  curr_pair = (int(walk[center_node_pos]), []) 
  UnboundLocalError: local variable 'center_node_pos' referenced before assignment

**Comment by xcgydfjjjderg** [comment]
> 能跑，就是结果不对，想跑的话可以调代码，不要再考虑改进了 &nbsp; 李琳 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年10月30日(星期天) 下午5:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [MysteryVaibhav/RWR-GAE] There is a big difference between the experimental data and the actual operation results (#3) 我也觉得我还打算用它开题，开题报告都写好了下周就开了但是我实验跑出来有差距，我尝试过调参但是也没效果。我给作者发邮件两个是假的，只有一个账号能发但是一直没收到回复。然后尝试按照代码输入参数，但是当我输入--context=1代码就报错。怎么办要死了。Traceback (most recent call last): File "train.py", line 201, in gae_for(args) File "train.py", line 120, in gae_for curr_pair = (int(walk[center_node_pos]), []) NameError: name 'center_node_pos' is not defined File "train.py", line 119, in gae_for curr_pair = (int(walk[center_node_pos]), []) UnboundLocalError: local variable 'center_node_pos' referenced before assignment — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

学姐很冒昧再次打扰您，真的非常对不起。我能最后在请教您一个问题吗，就是我在跑citeseer数据集的时候和原论文差距非常大我不知道为什么感觉很崩溃，是citeseer数据集部分的代码不对吗？在cora数据集还没啥问题但是在citeseer数据集上测试，问题非常大。只能厚着脸皮再来请教您，您当初遇见过这个问题吗？是不是有地方代码写的不对，您之前说想跑的话可以调代码，这地方是指调参还是我需要重写部分代码，还请您指教万分感谢，跪谢您。再次感谢您，好人一生平安！
